[package]
name = "incular-wgpu"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "wgpu rendering backend for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-core = { workspace = true }
incular-assets = { workspace = true }
incular-image = { workspace = true }
incular-rendering = { workspace = true }
incular-platform = { workspace = true }
wgpu = { workspace = true }
raw-window-handle = { workspace = true }
bytemuck = { workspace = true }
fontdue = { workspace = true }
lyon_tessellation = { workspace = true }
kurbo = { workspace = true }

[dev-dependencies]
incular-text = { workspace = true }
naga = { workspace = true, features = ["wgsl-in"] }
pollster = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "path_tessellation"
harness = false
