[package]
name = "incular-windows"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Windows platform integration for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-core = { workspace = true }
incular-config = { workspace = true }
incular-platform = { workspace = true }
incular-runtime = { workspace = true }
incular-wgpu = { workspace = true }
incular-layout = { workspace = true }
incular-widgets = { workspace = true }
winit = { workspace = true }
pollster = { workspace = true }
arboard = { workspace = true }
