[package]
name = "incular-config"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Renderer-independent configuration values for Incular"
readme = "README.md"
publish = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
icu_decimal = { workspace = true }
icu_datetime = { workspace = true }
icu_locale = { workspace = true }
icu_plurals = { workspace = true }
icu_provider = { workspace = true }
incular-core = { workspace = true }
