[package]
name = "incular-widgets"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Widgets, built-in components, and layout foundations for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-semantics = { workspace = true }
incular-core = { workspace = true }
incular-config = { workspace = true }
incular-gestures = { workspace = true }
incular-layout = { workspace = true }
incular-scroll = { workspace = true }
incular-rendering = { workspace = true }
incular-text = { workspace = true }
icu_segmenter = { workspace = true }
incular-animation = { workspace = true }
incular-assets = { workspace = true }
incular-image = { workspace = true }
serde_json = { workspace = true }
