[package]
name = "incular-macos"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "macOS platform integration for Incular"
readme = "README.md"
publish = true
license.workspace = true
repository.workspace = true
homepage.workspace = true

[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-desktop = { workspace = true }
incular-runtime = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
incular-platform = { workspace = true }
winit = { workspace = true }
objc2-app-kit = { workspace = true }

[features]
default = []
devtools = ["incular-desktop/devtools"]
