[package]
name = "incular"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "A Flutter-inspired GUI library for Rust"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[features]
default = ["desktop"]
desktop = ["dep:incular-platform", "dep:incular-wgpu", "dep:incular-linux", "dep:incular-windows", "dep:incular-macos"]

[dependencies]
incular-accessibility = { workspace = true }
incular-animation = { workspace = true }
incular-assets = { workspace = true }
incular-core = { workspace = true }
incular-layout = { workspace = true }
incular-macros = { workspace = true }
incular-painting = { workspace = true }
incular-platform = { workspace = true, optional = true }
incular-runtime = { workspace = true }
incular-text = { workspace = true }
incular-wgpu = { workspace = true, optional = true }
incular-widgets = { workspace = true }
incular-linux = { workspace = true, optional = true }
incular-windows = { workspace = true, optional = true }
incular-macos = { workspace = true, optional = true }
