[package]
name = "incular-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Platform-independent foundation types for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
kurbo = { workspace = true }
keyboard-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
palette = { workspace = true }
