[package]
name = "incular-text"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Text layout and typography foundations for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-assets = { workspace = true }
incular-core = { workspace = true }
incular-painting = { workspace = true }
fontdb = { workspace = true }
rustybuzz = { workspace = true }
unicode-linebreak = { workspace = true }
unicode-bidi = { workspace = true }
unicode-script = { workspace = true }
unicode-segmentation = { workspace = true }
ttf-parser = { workspace = true }
