[package]
name = "incular-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Shared platform abstractions for Incular"
readme = "README.md"
publish = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
[lints]
workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
directories = { workspace = true }
incular-core = { workspace = true }
keyboard-types = { workspace = true }
winit = { workspace = true }
raw-window-handle = { workspace = true }
