[package]
name = "incular-material"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Flutter Material-style controls for the Incular framework"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
typed-builder = { workspace = true }
incular-config = { workspace = true }
incular-controls = { workspace = true }
incular-core = { workspace = true }
incular-rendering = { workspace = true }
incular-semantics = { workspace = true }
incular-scroll = { workspace = true }
incular-text = { workspace = true }
incular-widgets = { workspace = true }
