[package]
name = "incular-macros"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Procedural macros for Incular"
readme = "README.md"
publish = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
[lints]
workspace = true

[lib]
path = "src/lib.rs"
proc-macro = true

[dependencies]
