[package]
name = "incular-android"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Android platform integration for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-core = { workspace = true }
incular-platform = { workspace = true }
