[package]
name = "incular-layout"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Layout primitives and algorithms for Incular"
readme = "README.md"
publish = true

[lib]
path = "src/lib.rs"

[dependencies]
incular-core = { workspace = true }
incular-config = { workspace = true }
